specfile_path: dist/wayrandr.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
    owner: "nikromen"
    project: "wayrandr"
    branch: main
    list_on_homepage: True
    preserve_project: True
