jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9
      - epel-10

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
      - epel-9
      - epel-10
    owner: "nikromen"
    project: "wayrandr"
    branch: main
    list_on_homepage: True
    preserve_project: True
